// Compact emoji set with searchable names. System emoji fonts render these
// natively (Segoe UI Emoji on Windows, Apple Color Emoji on macOS).
export interface EmojiItem { e: string; n: string }
export const EMOJI: { name: string; items: EmojiItem[] }[] = [
  {
    name: 'Smileys',
    items: [
      { e: '😀', n: 'grinning' }, { e: '😃', n: 'smiley' }, { e: '😄', n: 'smile' },
      { e: '😁', n: 'grin' }, { e: '😆', n: 'laughing' }, { e: '😅', n: 'sweat smile' },
      { e: '🤣', n: 'rofl' }, { e: '😂', n: 'joy' }, { e: '🙂', n: 'slightly smiling' },
      { e: '😉', n: 'wink' }, { e: '😊', n: 'blush' }, { e: '😇', n: 'innocent' },
      { e: '🥰', n: 'smiling hearts' }, { e: '😍', n: 'heart eyes' }, { e: '🤩', n: 'star struck' },
      { e: '😘', n: 'kiss' }, { e: '😋', n: 'yum' }, { e: '😜', n: 'stuck out tongue winking' },
      { e: '🤪', n: 'zany' }, { e: '😝', n: 'stuck out tongue' }, { e: '🤑', n: 'money mouth' },
      { e: '🤗', n: 'hugs' }, { e: '🤭', n: 'hand over mouth' }, { e: '🤫', n: 'shush' },
      { e: '🤔', n: 'thinking' }, { e: '🫡', n: 'salute' }, { e: '🤐', n: 'zipper mouth' },
      { e: '🤨', n: 'raised eyebrow' }, { e: '😐', n: 'neutral' }, { e: '😑', n: 'expressionless' },
      { e: '😶', n: 'no mouth' }, { e: '😏', n: 'smirk' }, { e: '😒', n: 'unamused' },
      { e: '🙄', n: 'eye roll' }, { e: '😬', n: 'grimacing' }, { e: '😌', n: 'relieved' },
      { e: '😔', n: 'pensive' }, { e: '😪', n: 'sleepy' }, { e: '🤤', n: 'drooling' },
      { e: '😴', n: 'sleeping' }, { e: '😷', n: 'mask' }, { e: '🤒', n: 'thermometer face' },
      { e: '🤕', n: 'bandage' }, { e: '🤢', n: 'nauseated' }, { e: '🤮', n: 'vomiting' },
      { e: '🥵', n: 'hot' }, { e: '🥶', n: 'cold' }, { e: '🥴', n: 'woozy' },
      { e: '😵', n: 'dizzy' }, { e: '🤯', n: 'exploding head' }, { e: '🤠', n: 'cowboy' },
      { e: '🥳', n: 'partying' }, { e: '😎', n: 'sunglasses' }, { e: '🤓', n: 'nerd' },
      { e: '🧐', n: 'monocle' }, { e: '😕', n: 'confused' }, { e: '😟', n: 'worried' },
      { e: '🙁', n: 'slightly frowning' }, { e: '😮', n: 'open mouth' }, { e: '😯', n: 'hushed' },
      { e: '😲', n: 'astonished' }, { e: '😳', n: 'flushed' }, { e: '🥺', n: 'pleading' },
      { e: '😢', n: 'cry' }, { e: '😭', n: 'sob' }, { e: '😱', n: 'scream' },
      { e: '😖', n: 'confounded' }, { e: '😞', n: 'disappointed' }, { e: '😓', n: 'downcast sweat' },
      { e: '😩', n: 'weary' }, { e: '😤', n: 'triumph' }, { e: '😡', n: 'rage' },
      { e: '😠', n: 'angry' }, { e: '🤬', n: 'cursing' }, { e: '💀', n: 'skull' },
      { e: '💩', n: 'poop' }, { e: '🤡', n: 'clown' }, { e: '👻', n: 'ghost' },
      { e: '👽', n: 'alien' }, { e: '🤖', n: 'robot' }, { e: '😺', n: 'smiley cat' },
      { e: '😹', n: 'joy cat' }, { e: '🙈', n: 'see no evil' }, { e: '🙉', n: 'hear no evil' },
      { e: '🙊', n: 'speak no evil' },
    ],
  },
  {
    name: 'Gestures',
    items: [
      { e: '👍', n: 'thumbs up' }, { e: '👎', n: 'thumbs down' }, { e: '👌', n: 'ok' },
      { e: '✌️', n: 'victory' }, { e: '🤞', n: 'crossed fingers' }, { e: '🤟', n: 'love you' },
      { e: '🤘', n: 'horns' }, { e: '👈', n: 'point left' }, { e: '👉', n: 'point right' },
      { e: '👆', n: 'point up' }, { e: '👇', n: 'point down' }, { e: '☝️', n: 'index up' },
      { e: '✋', n: 'raised hand' }, { e: '🤚', n: 'raised back' }, { e: '🖐️', n: 'hand splayed' },
      { e: '👋', n: 'wave' }, { e: '🤙', n: 'call me' }, { e: '💪', n: 'muscle' },
      { e: '🙏', n: 'pray' }, { e: '👏', n: 'clap' }, { e: '🙌', n: 'raised hands' },
      { e: '👐', n: 'open hands' }, { e: '🤲', n: 'palms up' }, { e: '🤝', n: 'handshake' },
      { e: '✍️', n: 'writing' }, { e: '💅', n: 'nail polish' }, { e: '🤌', n: 'pinched fingers' },
      { e: '🫶', n: 'heart hands' }, { e: '👊', n: 'fist' }, { e: '✊', n: 'raised fist' },
      { e: '🫵', n: 'point at you' }, { e: '🫰', n: 'snap' },
    ],
  },
  {
    name: 'Hearts',
    items: [
      { e: '❤️', n: 'red heart' }, { e: '🧡', n: 'orange heart' }, { e: '💛', n: 'yellow heart' },
      { e: '💚', n: 'green heart' }, { e: '💙', n: 'blue heart' }, { e: '💜', n: 'purple heart' },
      { e: '🖤', n: 'black heart' }, { e: '🤍', n: 'white heart' }, { e: '🤎', n: 'brown heart' },
      { e: '💔', n: 'broken heart' }, { e: '❣️', n: 'heart exclamation' }, { e: '💕', n: 'two hearts' },
      { e: '💞', n: 'revolving hearts' }, { e: '💓', n: 'beating heart' }, { e: '💗', n: 'growing heart' },
      { e: '💖', n: 'sparkling heart' }, { e: '💘', n: 'cupid' }, { e: '💝', n: 'heart ribbon' },
      { e: '💯', n: 'hundred' }, { e: '✨', n: 'sparkles' }, { e: '⭐', n: 'star' },
      { e: '🌟', n: 'glowing star' }, { e: '💫', n: 'dizzy star' }, { e: '🔥', n: 'fire' },
      { e: '💥', n: 'collision' }, { e: '🎉', n: 'party' }, { e: '🎊', n: 'confetti' },
    ],
  },
  {
    name: 'Objects',
    items: [
      { e: '📱', n: 'phone' }, { e: '💻', n: 'laptop' }, { e: '⌚', n: 'watch' },
      { e: '📷', n: 'camera' }, { e: '🎥', n: 'movie camera' }, { e: '🔍', n: 'magnifier' },
      { e: '💡', n: 'bulb' }, { e: '📚', n: 'books' }, { e: '📖', n: 'book' },
      { e: '📝', n: 'memo' }, { e: '✏️', n: 'pencil' }, { e: '📌', n: 'pin' },
      { e: '📎', n: 'paperclip' }, { e: '🔒', n: 'lock' }, { e: '🔑', n: 'key' },
      { e: '⏰', n: 'alarm' }, { e: '📅', n: 'calendar' }, { e: '🎁', n: 'gift' },
      { e: '🎈', n: 'balloon' }, { e: '🏆', n: 'trophy' }, { e: '⚽', n: 'soccer' },
      { e: '🏀', n: 'basketball' }, { e: '🎾', n: 'tennis' }, { e: '🎮', n: 'video game' },
      { e: '🎧', n: 'headphones' }, { e: '🎤', n: 'microphone' }, { e: '🎬', n: 'clapper' },
      { e: '🎨', n: 'art' }, { e: '☕', n: 'coffee' }, { e: '🍺', n: 'beer' },
      { e: '🍷', n: 'wine' }, { e: '🥂', n: 'champagne' }, { e: '🍰', n: 'cake' },
      { e: '🍕', n: 'pizza' }, { e: '🍔', n: 'burger' }, { e: '🥐', n: 'croissant' },
    ],
  },
  {
    name: 'Symbols',
    items: [
      { e: '✅', n: 'check mark' }, { e: '✔️', n: 'check' }, { e: '❌', n: 'cross' },
      { e: '⭕', n: 'circle' }, { e: '❗', n: 'exclamation' }, { e: '❓', n: 'question' },
      { e: '⚠️', n: 'warning' }, { e: '🚫', n: 'prohibited' }, { e: '♻️', n: 'recycle' },
      { e: '🔴', n: 'red circle' }, { e: '🟠', n: 'orange circle' }, { e: '🟡', n: 'yellow circle' },
      { e: '🟢', n: 'green circle' }, { e: '🔵', n: 'blue circle' }, { e: '🟣', n: 'purple circle' },
      { e: '➕', n: 'plus' }, { e: '➖', n: 'minus' }, { e: '➡️', n: 'right arrow' },
      { e: '⬆️', n: 'up arrow' }, { e: '🔝', n: 'top' }, { e: '🆕', n: 'new' },
      { e: '🆒', n: 'cool' }, { e: '🆓', n: 'free' }, { e: '🔔', n: 'bell' },
      { e: '🔕', n: 'no bell' }, { e: '💤', n: 'zzz' }, { e: '👀', n: 'eyes' },
      { e: '🧠', n: 'brain' }, { e: '🌍', n: 'earth' }, { e: '🌙', n: 'moon' },
      { e: '☀️', n: 'sun' }, { e: '🌈', n: 'rainbow' }, { e: '☁️', n: 'cloud' },
      { e: '🌊', n: 'wave' }, { e: '🌸', n: 'blossom' }, { e: '🌵', n: 'cactus' },
    ],
  },
]
