allowBuilds:
  '@whiskeysockets/baileys': false
  esbuild: true
  protobufjs: true

onlyBuiltDependencies:
  - electron
  - electron-winstaller
  - esbuild
  - protobufjs
  - sharp

overrides:
  libsignal: npm:libsignal-node@2.0.1

patchedDependencies:
  '@whiskeysockets/baileys@7.0.0-rc14': patches/@whiskeysockets__baileys@7.0.0-rc14.patch
